- Numpy means : **Numerical Python** or **number python**
- All the math operations can done by Numpy Package
- A student should understand the number representations
    - basic level is : **list and tuple**
    - list and tuple are not a vector representations
    - so thats why **Numpy**
- in Numpy we will represent the numbers called as **array**
- array means simply a list of numbers only but it is a vectors
- like numpy there is one more math package : **tensorflow**
- for cpu **numpy arrays are best**
- for gpu **tensorflow tensors are best**

In [ ]:
[10,20,30,40]    # scalar 
    |
array([10,20,30,40])    # array
    |
tensor([10,20,30,40])   # tensors (Google) Deep learning in

In [2]:
import numpy as np

In [3]:
np.__version__

'2.3.5'

In [4]:
l1 = [10,20,30,40,50]
np.array(l1)

array([10, 20, 30, 40, 50])

In [4]:
l1 = [10,20,30,40,50]
arr1 = np.array(l1)
arr1

array([10, 20, 30, 40, 50])

In [5]:
l2 = [1,2,3,4,5]
arr2 = np.array(l2)
arr2

array([1, 2, 3, 4, 5])

In [4]:
l1*l2

NameError: name 'l2' is not defined

In [6]:
arr1*arr2

array([ 10,  40,  90, 160, 250])

In [9]:
print(arr1)
print(arr2)
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[10 20 30 40 50]
[1 2 3 4 5]
[11 22 33 44 55]
[ 9 18 27 36 45]
[ 10  40  90 160 250]
[10. 10. 10. 10. 10.]


In [7]:
import time
start = time.time()
a = 10
b =20
c = a+b
print(c)
# l1 = range(1,10000000)
# l2 = range(1,10000000)
# ans = [i*j for i,j in zip(l1,l2)]
end = time.time()
print(f"The total time taken : {end - start}")

30
The total time taken : 0.0010979175567626953


In [12]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
import time
start = time.time()
l1 = np.arange(1,10000000)
l2 = np.arange(1,10000000)
ans = l1*l2
end = time.time()
print(f"The total time taken : {end - start}")

The total time taken : 0.20458722114562988
